# Generated by Django 4.2.3 on 2023-08-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='time_of_visit',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
